version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js 20...
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Pre-build phase...

  build:
    commands:
      - echo Building the Angular project...
      - ls -R dist/
      - npm run build

  post_build:
    commands:
      - echo Build completed...

artifacts:
  files:
    - "web-app/**/*" # Correct artifact path for your app
  base-directory: dist

cache:
  paths:
    - node_modules/**/*
