version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js 20...
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Pre-build phase...

  build:
    commands:
      - echo Building the Angular project...
      - npm run build -- --prod
      - echo Listing files in dist directory...
      - ls -R dist/web-app

  post_build:
    commands:
      - echo Build completed...

artifacts:
  files:
    - "dist/web-app/**/*" # Correct artifact path for your app
  base-directory: dist/web-app

cache:
  paths:
    - node_modules/**/*
